{% set name = "ipysheet" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c7123f5f25beb0d4a8f04222c0ad10b4bf6e48e7c2c86fbc13c4d2dc4b5b5dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python  >=3.6
    - setuptools
    - pip
    - jupyter-packaging
  run:
    - python  >=3.6
    - ipywidgets >=7.5.0,<8.0
    - pscript

test:
  imports:
    - ipysheet
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipysheet/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipysheet/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipysheet/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipysheet\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipysheet\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipysheet\\package.json (exit 1)          # [win]

about:
  home: http://github.com/QuantStack/ipysheet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spreadsheet widget for Jupyter
  description: Spreadsheet widget for Jupyter
  dev_url: https://github.com/QuantStack/ipysheet
  doc_url: https://ipysheet.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - SylvainCorlay
    - MaartenBreddels
    - martinRenou
